
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - share4recipe-network

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - share4recipe-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - share4recipe-network

networks:
  share4recipe-network:
    driver: bridge

volumes:
  postgres-data:
